package com.stardew.Network.Common.Packet;

public enum PacketType {
    MOVE,
    CHAT,
    LOGIN,
    WELCOME,
    PRESSKEYPACKET,
    GIVE_FLOWER_PACKET,
    HUGGING_PACKET,
    JOIN_LOBBY_PACKET,
    LEAVE_LOBBY_PACKET,
    MARRIAGE_PACKET,
    REACTION_PACKET,
    REFRESH_LOBBY_PACKET,
    RESTART_GAME_PACKET,
    SAVE_GAME_PACKET,
    SEND_MESSAGE_PACKET,
    SIGN_IN_PACKET,
    SIGN_UP_PACKET,
    START_GAME_PACKET,
    START_VOTING_PACKET,
    VOTE_PACKET,
    CREATE_LOBBY,
    SERVER_GENERAL_RESPOND_PACKET
}
